services:
  - type: web
    name: ronohs-decor-backend
    env: python
    region: frankfurt
    plan: free
    dependsOn:
      - ronohs-decor-db
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn ronohs_decor_backend.wsgi"
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ronohs-decor-db
          property: connectionStringStandard
      - key: CLOUDINARY_URL
        sync: false # Set manually in Render Dashboard
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DEBUG
        value: "False"
