# Generated by Django 5.2.4 on 2025-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social_links',
            field=models.JSONField(blank=True, help_text="e.g. {'twitter': 'url', 'linkedin': 'url'}", null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Optional caption for the featured image.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Brief description for search engines.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
