# Generated by Django 5.2.4 on 2025-07-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_threshold', models.PositiveIntegerField(help_text='Minimum quantity for this price')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_tiers', to='api.product')),
            ],
            options={
                'ordering': ['quantity_threshold'],
                'unique_together': {('product', 'quantity_threshold')},
            },
        ),
    ]
